---
abstract: 'Instantiate Moo classes with failover'
author:
  - 'Robert Rothenberg <rrwo@thermeon.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Failover
recommends:
  Class::Load::XS: '0'
requires:
  Carp: '0'
  Class::Load: '0.20'
  Moo: '0'
  Sub::Defer: '0'
  Sub::Quote: '0'
  Test::Most: '0'
  Types::Standard: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/robrwo/MooX-Failover/issues
  repository: git://github.com/robrwo/MooX-Failover.git
version: v0.2.1
